version: "3.7"

services:

  app:
    container_name: NodeJs_Challenge_20201030
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/NodeJs_Challenge_20201030/src
    ports:
      - "3000:3022"